# Generated by Django 5.2.3 on 2025-07-02 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('simulation_type', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript')], max_length=20, verbose_name='Simulyatsiya turi')),
                ('html_code', models.TextField(blank=True, verbose_name='HTML kodi')),
                ('css_code', models.TextField(blank=True, verbose_name='CSS kodi')),
                ('js_code', models.TextField(blank=True, verbose_name='JavaScript kodi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_public', models.BooleanField(default=True, verbose_name='Hammaga ochiq')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Simulyatsiya',
                'verbose_name_plural': 'Simulyatsiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='simulations.simulation', verbose_name='Simulyatsiya')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='simulations.simulation', verbose_name='Simulyatsiya')),
            ],
            options={
                'verbose_name': 'Yoqtirish',
                'verbose_name_plural': 'Yoqtirishlar',
                'unique_together': {('simulation', 'user')},
            },
        ),
    ]
