# Generated by Django 5.2.3 on 2025-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='simulation',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='simulation',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('kinematika', 'Kinematika'), ('dinamika', 'Dinamika'), ('statika', 'Statika'), ('moddaning_tuzilishi', 'Moddaning tuzilishi'), ('issiqlik_almashinuvi', 'Issiqlik almashinuvi'), ('termodinamika_qonunlari', 'Termodinamika qonunlari'), ('elektrostatika', 'Elektrostatika'), ('doimiy_tok', 'Doimiy tok'), ('magnit_maydon', 'Magnit maydon va induksiya'), ('ozgaruvchan_tok', "O'zgaruvchan tok"), ('geometrik_optika', 'Geometrik optika'), ('tolqinli_optika', "To'lqinli optika"), ('atom_tuzilishi', 'Atom tuzilishi'), ('radioaktivlik', 'Radioaktivlik'), ('yadro_fizikasi', 'Yadro fizikasi'), ('elementar_zarrachalar', 'Elementar zarrachalar')], max_length=30, null=True, verbose_name='Qism'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='html_code',
            field=models.TextField(verbose_name='HTML kodi'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='simulation_type',
            field=models.CharField(choices=[('mexanika', 'Mexanika'), ('molekulyar_fizika', 'Molekulyar fizika va termodinamika'), ('elektrodinamika', 'Elektrodinamika (elektr va magnit hodisalari)'), ('optika', 'Optika'), ('atom_yadro', 'Atom va yadro fizikasi')], max_length=20, verbose_name='Simulyatsiya turi'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
